name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  packages: write

jobs:
  PRBuildAndTest:
    if: github.event_name == 'pull_request'
    name: Build and Test for Pull Requests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnetSdkVersion: ["8.x"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnetSdkVersion }}
      - name: Restore NuGet packages
        run: dotnet restore src/app-two.sln
      - name: Build solution
        run: dotnet build src/app-two.sln --configuration Release --no-restore
      - name: Run Tests
        run: dotnet test src/app-two.sln --no-restore --verbosity normal
