name: Main Deployment

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to Production
    uses: ./.github/workflows/deploy.yml
    secrets:
      JWT_KEY: ${{ secrets.JWT_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
    with:
      port: ${{ vars.PORT }}
      docker_network: "oracle"
      container_name: app-two
